language: elixir
elixir: 1.11
otp_release: 23.0
jobs:
  include:
    - stage: test
      elixir: 1.7
      otp_release: 22.0.2
      script: &test_scripts
        - mix test
        - MIX_ENV=test mix credo --ignore Credo.Check.Design.TagTODO
    - stage: test
      otp_release: 22.3
      script: *test_scripts
    - stage: test
      script: *test_scripts
    - stage: deploy
      script: skip
      deploy:
        provider: script
        script: mix hex.publish --yes
        skip_cleanup: true
        on:
          tags: true
          all_branches: true